networks:
  peercmpe273:
    driver: bridge
    ipam:
      config:
      - subnet: 172.59.0.0/16
      driver: default
services:
  app:
    build: ./app
    networks:
    - peercmpe273
    ports:
    - 39667:5000
    - 58042:2006
    - 31451:2007
    volumes:
    - ./ports.ini:/app/ports.ini
version: '2.2'
